## Import Libraries

In [88]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# For training and splitting data
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

## Acquire and Explore Data

In [142]:
# Import csv files

buyer_lead_df = pd.read_csv("Phirst_Buyer_Lead.csv") # Buyers' responses

soma1_df = pd.read_csv("SOMA1_Availability.csv") # Availability of houses in SOMA1
soma2_df = pd.read_csv("SOMA2_Availability.csv") # Avaiability of houses in SOMA2 
soma3_df = pd.read_csv("SOMA3_Availability.csv") # Avaiability of houses in SOMA3
vismin_df = pd.read_csv("VISMIN_Availability.csv") # Avaiability of houses in VISMIN

### Explore Buyer Responses Data

In [143]:
# See the first 5 rows of buyer data

buyer_lead_df.head()

,Timestamp,Date,"Principal Buyer Full Name (First M.I., Family)",Age,Income of Principal Buyer,Marital Status,No. of Family Members,Preferred Location,SOURCE OF LEAD,Source of Income,Employer,Preferred Pay Term,"Spouse Full Name (First M.I., Family)",Age of Spouse,Income of Spouse
0,01/05/2024 19:22,01/05/2024,Client 1,29,"PHP 125,500",Married,7,BATULAO,Facebook Ads,Locally Employed,bdo unibank,20-80 Pagibig Financing,Spouse of Client 1,30,"PHP 83,000"
1,01/06/2024 11:56,01/06/2024,Client 2,27,"PHP 61,000",Married,2,MAGALANG EAST,Facebook Ads,Self Employed/ Business Owner,independent contractor,20-80 Pagibig Financing,Spouse of Client 2,25,"PHP 42,500"
2,01/11/2024 20:54,01/11/2024,Client 3,42,"PHP 247,000",Single,N/a,GAPAN,Broker/Agent,OFW Land base,Aramco,20-80 Pagibig Financing,N/a,N/a,N/a
3,01/15/2024 14:35:29,01/15/2024,Client 4,47,"PHP 32,500",Single,NaN,LIPA,Facebook Ads,OFW Land base,pricewaterhousecoopers uae,20-80 Pagibig Financing,NaN,NaN,NaN
4,01/17/2024 17:33:44,01/17/2024,Client 5,27,"PHP 243,000",Married,2,TAYABAS,Facebook Ads,OFW Land base,Hyundai engineering,20-80 Pagibig Financing,Spouse of Client 5,28,"PHP 224,500"

In [144]:
# See how many rows and columns there are
print("Total number of rows and columns:", buyer_lead_df.shape)

# Check for missing values
print("\nMissing values:")
print(buyer_lead_df.isnull().sum()) 

# Check the information 
print("\nInformation: ")
print(buyer_lead_df.info())

Total number of rows and columns: (600, 15)

Missing values:
Timestamp                                           0
Date                                                0
Principal Buyer Full Name (First M.I., Family)      0
Age                                                 0
Income of Principal Buyer                           0
Marital Status                                      0
No. of Family Members                             174
Preferred Location                                  0
SOURCE OF LEAD                                      0
Source of Income                                    0
Employer                                            0
Preferred Pay Term                                  0
Spouse Full Name (First M.I., Family)             183
Age of Spouse                                     183
Income of Spouse                                  183
dtype: int64

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 15 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Timestamp                                       600 non-null    object
 1   Date                                            600 non-null    object
 2   Principal Buyer Full Name (First M.I., Family)  600 non-null    object
 3   Age                                             600 non-null    int64
 4   Income of Principal Buyer                       600 non-null    object
 5   Marital Status                                  600 non-null    object
 6   No. of Family Members                           426 non-null    object
 7   Preferred Location                              600 non-null    object
 8   SOURCE OF LEAD                                  600 non-null    object
 9   Source of Income                                600 non-null    object
 10  Employer                                        600 non-null    object
 11  Preferred Pay Term                              600 non-null    object
 12  Spouse Full Name (First M.I., Family)           417 non-null    object
 13  Age of Spouse                                   417 non-null    object
 14  Income of Spouse                                417 non-null    object
dtypes: int64(1), object(14)
memory usage: 70.4+ KB
None

In [145]:
# Clean the data and keep only necessary ones
# Rows with null values for columns 'Age of Spouse' and 'Income of Spouse' will be kept since not all buyers have spouses

buyer_lead_df = buyer_lead_df.drop(columns=['Timestamp', 'Date', 'Principal Buyer Full Name (First M.I., Family)', 'Employer', 'Spouse Full Name (First M.I., Family)'])

buyer_lead_df # shows the updated data

,Age,Income of Principal Buyer,Marital Status,No. of Family Members,Preferred Location,SOURCE OF LEAD,Source of Income,Preferred Pay Term,Age of Spouse,Income of Spouse
0,29,"PHP 125,500",Married,7,BATULAO,Facebook Ads,Locally Employed,20-80 Pagibig Financing,30,"PHP 83,000"
1,27,"PHP 61,000",Married,2,MAGALANG EAST,Facebook Ads,Self Employed/ Business Owner,20-80 Pagibig Financing,25,"PHP 42,500"
2,42,"PHP 247,000",Single,N/a,GAPAN,Broker/Agent,OFW Land base,20-80 Pagibig Financing,N/a,N/a
3,47,"PHP 32,500",Single,NaN,LIPA,Facebook Ads,OFW Land base,20-80 Pagibig Financing,NaN,NaN
4,27,"PHP 243,000",Married,2,TAYABAS,Facebook Ads,OFW Land base,20-80 Pagibig Financing,28,"PHP 224,500"
...,...,...,...,...,...,...,...,...,...,...
595,37,"PHP 209,000",Single,N/a,BATULAO,Broker/Agent,OFW Land base,20-80 Pagibig Financing,N/a,N/a
596,52,"PHP 35,000",Married,7,GEN TRI,Facebook Ads,OFW Land base,20-80 Pagibig Financing,52,"PHP 28,000"
597,25,"PHP 65,500",Widow,NaN,BALIWAG,Broker/Agent,OFW Sea Base,20-80 Pagibig Financing,NaN,NaN
598,55,"PHP 113,000",Married,7,LIPA,Referral,OFW Land base,20-80 Pagibig Financing,60,"PHP 81,500"
599,36,"PHP 114,000",Single,NaN,STO. TOMAS,Facebook Ads,Locally Employed,20-80 Pagibig Financing,NaN,NaN

### Explore SOMA1 Availability Data

In [93]:
# Check the first 5 rows of SOMA1 data
soma1_df.head()

,Unit Code,GEO,PROJECT,PHASE,SUB PHASE,BATCH,UNIT TYPE,LOT AREA,FLOOR AREA,TCP,VAT,TCP w/o VAT,ETD,S HOUSECON,SU & INVENTORY,APPLICABLE TERM,HOUSECON REMARKS,Unnamed: 17
0,B022L001,SOMA1,GEN TRI,3,B,1,UNNA CORNER,137,54,"6,145,947.00","614,597.87","5,531,349.13",Oct-27,0%,0%,OPEN,MEMO TERM,YELLOW TAG
1,B022L030,SOMA1,GEN TRI,3,B,1,UNNA CORNER,139,54,"6,031,025.00","603,109.87","5,427,915.13",Oct-27,0%,0%,OPEN,MEMO TERM,YELLOW TAG
2,B022L034,SOMA1,GEN TRI,3,B,1,UNNA CORNER,153,54,"6,352,645.00","635,265.55","5,717,379.45",Nov-27,0%,0%,OPEN,MEMO TERM,YELLOW TAG
3,B022L036,SOMA1,GEN TRI,3,B,1,UNNA CORNER,138,54,"6,008,088.00","600,813.03","5,407,274.97",Nov-27,0%,0%,OPEN,MEMO TERM,YELLOW TAG
4,B023L001,SOMA1,GEN TRI,3,B,1,UNNA CORNER,133,54,"5,926,361.00","480,000.01","5,446,360.99",Nov-27,17%,17%,OPEN,MEMO TERM,YELLOW TAG

In [85]:
# Check how many rows and columns the data has
print("Total number of rows and columns:", soma1_df.shape)

# Check for missing values
print("\nMissing values:")
print(soma1_df.isnull().sum())

# Check the information of all the data
print("\nInformation: ")
soma1_df.info()

Total number of rows and columns: (633, 18)

Missing values:
Unit Code             0
GEO                   0
PROJECT               0
PHASE                 0
SUB PHASE           293
BATCH                 0
UNIT TYPE             0
LOT AREA              0
FLOOR AREA            0
TCP                   0
VAT                   2
TCP w/o VAT           0
ETD                   0
S HOUSECON            0
SU & INVENTORY        0
APPLICABLE TERM       0
HOUSECON REMARKS      0
Unnamed: 17           0
dtype: int64

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 633 entries, 0 to 632
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unit Code         633 non-null    object
 1   GEO               633 non-null    object
 2   PROJECT           633 non-null    object
 3   PHASE             633 non-null    int64
 4   SUB PHASE         340 non-null    object
 5   BATCH             633 non-null    object
 6   UNIT TYPE         633 non-null    object
 7   LOT AREA          633 non-null    int64
 8   FLOOR AREA        633 non-null    int64
 9   TCP               633 non-null    object
 10  VAT               631 non-null    object
 11  TCP w/o VAT       633 non-null    object
 12  ETD               633 non-null    object
 13  S HOUSECON        633 non-null    object
 14  SU & INVENTORY    633 non-null    object
 15  APPLICABLE TERM   633 non-null    object
 16  HOUSECON REMARKS  633 non-null    object
 17  Unnamed: 17       633 non-null    object
dtypes: int64(3), object(15)
memory usage: 89.1+ KB

Total duplicate units: 82

In [96]:
# Clean the data and keep only necessary ones

soma1_df = soma1_df.drop(columns=['GEO', 'PHASE', 'SUB PHASE', 'BATCH', 'FLOOR AREA', 'VAT', 'ETD', 'S HOUSECON', 'SU & INVENTORY', 'APPLICABLE TERM', 'HOUSECON REMARKS', 'Unnamed: 17'])

soma1_df # shows the updated data

,Unit Code,PROJECT,UNIT TYPE,LOT AREA,TCP,TCP w/o VAT
0,B022L001,GEN TRI,UNNA CORNER,137,"6,145,947.00","5,531,349.13"
1,B022L030,GEN TRI,UNNA CORNER,139,"6,031,025.00","5,427,915.13"
2,B022L034,GEN TRI,UNNA CORNER,153,"6,352,645.00","5,717,379.45"
3,B022L036,GEN TRI,UNNA CORNER,138,"6,008,088.00","5,407,274.97"
4,B023L001,GEN TRI,UNNA CORNER,133,"5,926,361.00","5,446,360.99"
...,...,...,...,...,...,...
628,B009L007,BALIWAG EXPANSION,CALISTA END,66,"3,299,878.00","3,299,878.00"
629,B009L027,BALIWAG EXPANSION,CALISTA END,66,"3,299,878","3,299,878"
630,B029L007,GAPAN,CALISTA MID,44,"1,969,092","1,969,092"
631,B029L006,GAPAN,CALISTA MID,44,"1,969,092.00","1,969,092.00"
632,B007L037,BALIWAG EXPANSION,CALISTA MID,44,"2,506,224.00","2,506,224.00"

In [97]:
# Check for duplicate values
print("\nTotal duplicate units:", clean[['Unit Code']].duplicated().sum())

Total duplicate units: 82

In [98]:
# Drop the duplicated Unit Code rows
soma1_df = soma1_df.drop_duplicates(subset = 'Unit Code', keep = 'last')

# Prints the updated information without duplicates
soma1_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 551 entries, 1 to 632
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unit Code    551 non-null    object
 1   PROJECT      551 non-null    object
 2   UNIT TYPE    551 non-null    object
 3   LOT AREA     551 non-null    int64
 4   TCP          551 non-null    object
 5   TCP w/o VAT  551 non-null    object
dtypes: int64(1), object(5)
memory usage: 30.1+ KB

### Explore SOMA2 Availability Data

In [99]:
# Check the first 5 rows of SOMA2 data
soma2_df.head()

,UNIT CODE,COM,GEO,PROJECT,PHASE,SUB PHASE,BATCH,UNIT TYPE,LOT AREA,FLOOR AREA,TCP,VAT,TCP w/o VAT,ESTIMATED TURNOVER DATE,S HOUSECON,SU & INVENTORY,APPLICABLE TERM,HOUSE CON TAG,Unnamed: 18,Unnamed: 19
0,B044L009,PPHI,SOMA2,TAYABAS,1.0,B,1,CALISTA MID,44,40.0,"1,813,157.71",0.00,"1,813,157.71",Aug-2025,100%,80%,OPEN,RSBS WITHIN THE MONTH,RED TAG,NaN
1,B044L011,PPHI,SOMA2,TAYABAS,1.0,B,1,CALISTA MID,44,40.0,"1,813,157.71",0.00,"1,813,157.71",Aug-2025,100%,80%,OPEN,RSBS WITHIN THE MONTH,RED TAG,NaN
2,B044L019,PPHI,SOMA2,TAYABAS,1.0,B,1,CALISTA MID,44,40.0,"1,813,157.71",0.00,"1,813,157.71",Aug-2025,100%,80%,OPEN,RSBS WITHIN THE MONTH,RED TAG,NaN
3,B044L021,PPHI,SOMA2,TAYABAS,1.0,B,1,CALISTA MID,44,40.0,"1,813,157.71",0.00,"1,813,157.71",Aug-2025,100%,80%,OPEN,RSBS WITHIN THE MONTH,RED TAG,NaN
4,B044L040,PPHI,SOMA2,TAYABAS,1.0,B,1,CALISTA MID,44,40.0,"1,789,537.65",0.00,"1,789,537.65",Aug-2025,100%,80%,OPEN,RSBS WITHIN THE MONTH,RED TAG,NaN

In [102]:
# Check how many rows and columns the data has
print("Total number of rows and columns:", soma2_df.shape)

# Check for missing values
print("\nMissing values:")
print(soma2_df.isnull().sum())

# Check the information of all the data
print("\nInformation: ")
soma2_df.info()

Total number of rows and columns: (3345, 20)

Missing values:
UNIT CODE                  1978
COM                        1978
GEO                        1978
PROJECT                    1978
PHASE                      1978
SUB PHASE                  2532
BATCH                      1992
UNIT TYPE                  1978
LOT AREA                   1978
FLOOR AREA                 1992
TCP                        1978
VAT                        2152
TCP w/o VAT                1978
ESTIMATED TURNOVER DATE    1978
S HOUSECON                 1978
SU & INVENTORY             1978
APPLICABLE TERM            1978
HOUSE CON TAG              1978
Unnamed: 18                1978
Unnamed: 19                3345
dtype: int64

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3345 entries, 0 to 3344
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UNIT CODE                1367 non-null   object
 1   COM                      1367 non-null   object
 2   GEO                      1367 non-null   object
 3   PROJECT                  1367 non-null   object
 4   PHASE                    1367 non-null   float64
 5   SUB PHASE                813 non-null    object
 6   BATCH                    1353 non-null   object
 7   UNIT TYPE                1367 non-null   object
 8   LOT AREA                 1367 non-null   object
 9   FLOOR AREA               1353 non-null   float64
 10  TCP                      1367 non-null   object
 11  VAT                      1193 non-null   object
 12  TCP w/o VAT              1367 non-null   object
 13  ESTIMATED TURNOVER DATE  1367 non-null   object
 14  S HOUSECON               1367 non-null   object
 15  SU & INVENTORY           1367 non-null   object
 16  APPLICABLE TERM          1367 non-null   object
 17  HOUSE CON TAG            1367 non-null   object
 18  Unnamed: 18              1367 non-null   object
 19  Unnamed: 19              0 non-null      float64
dtypes: float64(3), object(17)
memory usage: 522.8+ KB

In [107]:
# Clean the data and keep only necessary ones

soma2_df = soma2_df.drop(columns=['COM', 'GEO', 'PHASE', 'SUB PHASE', 'BATCH', 'FLOOR AREA', 'VAT', 'ESTIMATED TURNOVER DATE', 'S HOUSECON', 'SU & INVENTORY', 'APPLICABLE TERM', 'HOUSE CON TAG', 'Unnamed: 18', 'Unnamed: 19'])

soma2_df # shows the updated data

     UNIT CODE  PROJECT    UNIT TYPE LOT AREA           TCP   TCP w/o VAT
0     B044L009  TAYABAS  CALISTA MID       44  1,813,157.71  1,813,157.71
1     B044L011  TAYABAS  CALISTA MID       44  1,813,157.71  1,813,157.71
2     B044L019  TAYABAS  CALISTA MID       44  1,813,157.71  1,813,157.71
3     B044L021  TAYABAS  CALISTA MID       44  1,813,157.71  1,813,157.71
4     B044L040  TAYABAS  CALISTA MID       44  1,789,537.65  1,789,537.65
...        ...      ...          ...      ...           ...           ...
3340       NaN      NaN          NaN      NaN           NaN           NaN
3341       NaN      NaN          NaN      NaN           NaN           NaN
3342       NaN      NaN          NaN      NaN           NaN           NaN
3343       NaN      NaN          NaN      NaN           NaN           NaN
3344       NaN      NaN          NaN      NaN           NaN           NaN

[3345 rows x 6 columns]

In [116]:
# Drop rows with null values

soma2_df = soma2_df.dropna()
soma2_df.shape # shows how many rows there are with no null values

(1367, 6)

In [118]:
# Check for duplicate values
print("\nTotal duplicate units:", soma2_df[['UNIT CODE']].duplicated().sum())

Total duplicate units: 145

In [122]:
# Drop the duplicated Unit Code rows
soma2_df = soma2_df.drop_duplicates(subset = 'UNIT CODE', keep = 'last')

# Prints the updated information without duplicates
soma2_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1222 entries, 0 to 1366
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   UNIT CODE    1222 non-null   object
 1   PROJECT      1222 non-null   object
 2   UNIT TYPE    1222 non-null   object
 3   LOT AREA     1222 non-null   object
 4   TCP          1222 non-null   object
 5   TCP w/o VAT  1222 non-null   object
dtypes: object(6)
memory usage: 66.8+ KB

### Explore SOMA3 Availability Data

In [123]:
# Check the first 5 rows of SOMA1 data
soma3_df.head()

,UNIT CODE,GEO,PROJECT,PHASE,SUB PHASE,BATCH,UNIT TYPE,LOT AREA,FLOOR AREA,TCP,VAT,TCP w/o VAT,ESTIMATED TURNOVER DATE,S HOUSECON,SU & INVENTORY,APPLICABLE TERM,HOUSE CON TAG,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,B041L065,SOMA3,LIPA,1.0,A,1,CALISTA MID,44.0,40.0,"1,999,907.00",0.00,"1,999,907.00",Dec-2026,80%,REOPEN,RSBS WITHIN THE MONTH,RED TAG,NaN,NaN,NaN
1,B042L047,SOMA3,LIPA,1.0,A,2,CALISTA MID,44.0,40.0,"1,999,907.00",0,"1,999,907.00",Dec-2026,80%,REOPEN,RSBS WITHIN THE MONTH,RED TAG,NaN,NaN,NaN
2,B042L043,SOMA3,LIPA,1.0,A,2,CALISTA MID,44.0,40.0,"1,999,907.00",0,"1,999,907.00",Dec-2026,80%,REOPEN,RSBS WITHIN THE MONTH,RED TAG,NaN,NaN,NaN
3,B032L020,SOMA3,BATULAO,1.0,A,3,CALISTA END,147.0,40.0,"5,824,953.00","582,499","5,242,455.00",May-2025,80%,REOPEN,RSBS WITHIN THE MONTH,RED TAG,NaN,NaN,NaN
4,B004L003,SOMA3,EDITIONS BATULAO VOL. 1,2.0,NaN,1,CORIN,188.0,120.0,"10,837,123.00","1,083,720","9,753,403.00",Feb-2026,60%,OPEN,MEMO TERMS,RED TAG,NaN,NaN,NaN

In [124]:
# Check how many rows and columns the data has
print("Total number of rows and columns:", soma3_df.shape)

# Check for missing values
print("\nMissing values:")
print(soma3_df.isnull().sum())

# Check the information of all the data
print("\nInformation: ")
soma3_df.info()

Total number of rows and columns: (802, 20)

Missing values:
UNIT CODE                   19
GEO                         19
PROJECT                     19
PHASE                       19
SUB PHASE                  418
BATCH                       61
UNIT TYPE                   19
LOT AREA                    19
FLOOR AREA                  33
TCP                         19
VAT                        456
TCP w/o VAT                 19
ESTIMATED TURNOVER DATE     61
S HOUSECON                  18
SU & INVENTORY              19
APPLICABLE TERM             19
HOUSE CON TAG               19
Unnamed: 17                802
Unnamed: 18                802
Unnamed: 19                802
dtype: int64

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 802 entries, 0 to 801
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UNIT CODE                783 non-null    object
 1   GEO                      783 non-null    object
 2   PROJECT                  783 non-null    object
 3   PHASE                    783 non-null    float64
 4   SUB PHASE                384 non-null    object
 5   BATCH                    741 non-null    object
 6   UNIT TYPE                783 non-null    object
 7   LOT AREA                 783 non-null    float64
 8   FLOOR AREA               769 non-null    float64
 9   TCP                      783 non-null    object
 10  VAT                      346 non-null    object
 11  TCP w/o VAT              783 non-null    object
 12  ESTIMATED TURNOVER DATE  741 non-null    object
 13  S HOUSECON               784 non-null    object
 14  SU & INVENTORY           783 non-null    object
 15  APPLICABLE TERM          783 non-null    object
 16  HOUSE CON TAG            783 non-null    object
 17  Unnamed: 17              0 non-null      float64
 18  Unnamed: 18              0 non-null      float64
 19  Unnamed: 19              0 non-null      float64
dtypes: float64(6), object(14)
memory usage: 125.4+ KB

In [125]:
# Clean the data and keep only necessary ones

soma3_df = soma3_df.drop(columns=['GEO', 'PHASE', 'SUB PHASE', 'BATCH', 'FLOOR AREA', 'VAT', 'ESTIMATED TURNOVER DATE', 'S HOUSECON', 'SU & INVENTORY', 'APPLICABLE TERM', 'HOUSE CON TAG', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19'])

soma3_df # shows the updated data

,UNIT CODE,PROJECT,UNIT TYPE,LOT AREA,TCP,TCP w/o VAT
0,B041L065,LIPA,CALISTA MID,44.0,"1,999,907.00","1,999,907.00"
1,B042L047,LIPA,CALISTA MID,44.0,"1,999,907.00","1,999,907.00"
2,B042L043,LIPA,CALISTA MID,44.0,"1,999,907.00","1,999,907.00"
3,B032L020,BATULAO,CALISTA END,147.0,"5,824,953.00","5,242,455.00"
4,B004L003,EDITIONS BATULAO VOL. 1,CORIN,188.0,"10,837,123.00","9,753,403.00"
...,...,...,...,...,...,...
797,NaN,NaN,NaN,NaN,NaN,NaN
798,NaN,NaN,NaN,NaN,NaN,NaN
799,NaN,NaN,NaN,NaN,NaN,NaN
800,NaN,NaN,NaN,NaN,NaN,NaN
801,NaN,NaN,NaN,NaN,NaN,NaN

In [126]:
# Drop rows with null values

soma3_df = soma3_df.dropna()
soma3_df.shape # shows how many rows there are with no null values

(783, 6)

In [129]:
# Check for duplicate values
print("\nTotal duplicate units:", soma3_df[['UNIT CODE']].duplicated().sum())

Total duplicate units: 52

In [130]:
# Drop the duplicated Unit Code rows
soma3_df = soma3_df.drop_duplicates(subset = 'UNIT CODE', keep = 'last')

# Prints the updated information without duplicates
soma3_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 731 entries, 0 to 782
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   UNIT CODE    731 non-null    object
 1   PROJECT      731 non-null    object
 2   UNIT TYPE    731 non-null    object
 3   LOT AREA     731 non-null    float64
 4   TCP          731 non-null    object
 5   TCP w/o VAT  731 non-null    object
dtypes: float64(1), object(5)
memory usage: 40.0+ KB

### Explore VISMIN Availability Data

In [131]:
# Check the first 5 rows of SOMA1 data
vismin_df.head()

,UNIT CODE,GEO,PROJECT,PHASE,SUB PHASE,BATCH,UNIT TYPE,LOT AREA,FLOOR AREA,TCP,...,TCP w/o VAT,ESTIMATED TURNOVER,HOUSE CON,INVENTORY STATUS,HOLDING STATUS,HOUSE TAGGING,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,B024L044,VISMIN,BACOLOD,1.0,A,2.0,AMANI END,157.0,36.0,"3,359,781.43",...,"3,359,781.43",Jan-2026,100%,REOPEN,RSBS WITHI THIS MONTH,RED TAGGING,NaN,NaN,NaN,NaN
1,B030L002,VISMIN,BACOLOD,1.0,A,5.0,AMANI END,161.0,36.0,"3,593,445.34",...,"3,593,445.34",Oct-2026,0%,OPEN,MEMO TERMS,YELLOW TAGGING,NaN,NaN,NaN,NaN
2,B032L008,VISMIN,BACOLOD,1.0,A,5.0,AMANI END,142.0,36.0,"3,328,360.61",...,"3,328,360.61",Dec-2026,12%,OPEN,MEMO TERMS,YELLOW TAGGING,NaN,NaN,NaN,NaN
3,B033L001,VISMIN,BACOLOD,1.0,A,5.0,AMANI END CORNER,210.0,36.0,"4,371,998.44",...,"4,371,998.44",Dec-2026,0%,OPEN,MEMO TERMS,YELLOW TAGGING,NaN,NaN,NaN,NaN
4,B033L002,VISMIN,BACOLOD,1.0,A,5.0,AMANI END,153.0,36.0,"3,450,822.75",...,"3,450,822.75",Dec-2026,0%,OPEN,MEMO TERMS,YELLOW TAGGING,NaN,NaN,NaN,NaN

In [132]:
# Check how many rows and columns the data has
print("Total number of rows and columns:", vismin_df.shape)

# Check for missing values
print("\nMissing values:")
print(vismin_df.isnull().sum())

# Check the information of all the data
print("\nInformation: ")
vismin_df.info()

Total number of rows and columns: (1120, 21)

Missing values:
UNIT CODE              720
GEO                    720
PROJECT                720
PHASE                  720
SUB PHASE             1004
BATCH                  720
UNIT TYPE              720
LOT AREA               720
FLOOR AREA             720
TCP                    720
VAT                    932
TCP w/o VAT            720
ESTIMATED TURNOVER     848
HOUSE CON              720
INVENTORY STATUS       720
HOLDING STATUS         720
HOUSE TAGGING          720
Unnamed: 17           1120
Unnamed: 18           1120
Unnamed: 19           1120
Unnamed: 20           1120
dtype: int64

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1120 entries, 0 to 1119
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   UNIT CODE           400 non-null    object
 1   GEO                 400 non-null    object
 2   PROJECT             400 non-null    object
 3   PHASE               400 non-null    float64
 4   SUB PHASE           116 non-null    object
 5   BATCH               400 non-null    float64
 6   UNIT TYPE           400 non-null    object
 7   LOT AREA            400 non-null    float64
 8   FLOOR AREA          400 non-null    float64
 9   TCP                 400 non-null    object
 10  VAT                 188 non-null    object
 11  TCP w/o VAT         400 non-null    object
 12  ESTIMATED TURNOVER  272 non-null    object
 13  HOUSE CON           400 non-null    object
 14  INVENTORY STATUS    400 non-null    object
 15  HOLDING STATUS      400 non-null    object
 16  HOUSE TAGGING       400 non-null    object
 17  Unnamed: 17         0 non-null      float64
 18  Unnamed: 18         0 non-null      float64
 19  Unnamed: 19         0 non-null      float64
 20  Unnamed: 20         0 non-null      float64
dtypes: float64(8), object(13)
memory usage: 183.9+ KB

In [136]:
# Clean the data and keep only necessary ones

vismin_df = vismin_df.drop(columns=['GEO', 'PHASE', 'SUB PHASE', 'BATCH', 'FLOOR AREA', 'VAT', 'ESTIMATED TURNOVER', 'HOUSE CON', 'INVENTORY STATUS', 'HOLDING STATUS', 'HOUSE TAGGING', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20'])

vismin_df # shows the updated data

,UNIT CODE,PROJECT,UNIT TYPE,LOT AREA,TCP,TCP w/o VAT
0,B024L044,BACOLOD,AMANI END,157.0,"3,359,781.43","3,359,781.43"
1,B030L002,BACOLOD,AMANI END,161.0,"3,593,445.34","3,593,445.34"
2,B032L008,BACOLOD,AMANI END,142.0,"3,328,360.61","3,328,360.61"
3,B033L001,BACOLOD,AMANI END CORNER,210.0,"4,371,998.44","4,371,998.44"
4,B033L002,BACOLOD,AMANI END,153.0,"3,450,822.75","3,450,822.75"
...,...,...,...,...,...,...
1115,NaN,NaN,NaN,NaN,NaN,NaN
1116,NaN,NaN,NaN,NaN,NaN,NaN
1117,NaN,NaN,NaN,NaN,NaN,NaN
1118,NaN,NaN,NaN,NaN,NaN,NaN
1119,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
# Drop rows with null values

vismin_df = vismin_df.dropna()
vismin_df.shape # shows how many rows there are with no null values

(400, 6)

In [139]:
# Check for duplicate values
print("\nTotal duplicate units:", vismin_df[['UNIT CODE']].duplicated().sum())

Total duplicate units: 24

In [141]:
# Drop the duplicated Unit Code rows
vismin_df = vismin_df.drop_duplicates(subset = 'UNIT CODE', keep = 'last')

# Prints the updated information without duplicates
vismin_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 376 entries, 0 to 399
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   UNIT CODE    376 non-null    object
 1   PROJECT      376 non-null    object
 2   UNIT TYPE    376 non-null    object
 3   LOT AREA     376 non-null    float64
 4   TCP          376 non-null    object
 5   TCP w/o VAT  376 non-null    object
dtypes: float64(1), object(5)
memory usage: 20.6+ KB